packages:
  - apps/*
  - packages/*

catalog:
  "@better-auth/cli": ^1.4.5
  "@better-auth/expo": ^1.4.5
  "@kyh/eslint-config": ^1.1.10
  "@kyh/prettier-config": ^1.1.10
  "@kyh/tsconfig": ^1.1.10
  "@tailwindcss/postcss": ^4.1.17
  "@tailwindcss/vite": ^4.1.17
  "@tanstack/react-form": ^1.27.1
  "@tanstack/react-query": ^5.90.12
  "@trpc/client": ^11.7.2
  "@trpc/server": ^11.7.2
  "@trpc/tanstack-react-query": ^11.7.2
  "@types/node": ^24.10.1
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^5.1.2
  better-auth: ^1.4.5
  eslint: ^9.39.1
  next: ^16.0.7
  prettier: ^3.7.4
  react: ^19.2.1
  react-dom: ^19.2.1
  superjson: ^2.2.6
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  vite: ^7.2.7
  zod: ^4.1.13

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
